name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Go Version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
